### PR TITLE
Website redesign..

### PR DESCRIPTION
**Pull request by teamblitz8**
Website in redesign to better align with values, brand etc
Aims to fix major bugs in the last version of website, namely the mobile interface

Each commit will be in chunks.

### CODE REVIEW

**Comment by teamblitz8** [comment]
Milestone reached: Homepage complete!

1 of 10 milestones reached:
Complete homepage ✅
Complete about page
Complete journey page
Complete work page
Complete sponsor page
Complete blog main page
Complete blog template page
Complete contact page
Allow mobile compatibility
Replace all placeholder media

**Comment by poggestcheese** [comment]
Milestones reached: About Us, Our Journey, Our Work pages complete!

4 of ~~10~~ **8** milestones reached:
Complete homepage ✅
Complete about page ✅
* ~~Sorting/filtering/search system~~

Complete journey page ✅
Complete work page ✅
Complete sponsor page
~~Complete blog main page~~
~~Complete blog template page~~
Complete contact page
Complete 404 page
Allow mobile compatibility
Replace all placeholder media 🚧

**Comment by teamblitz8** [comment]
cba gonna merge now

**Review by teamblitz8 — COMMENTED** [review]
skibidee

**Pull request merged**
